### ISSUE TITLE
Запрос сертификатов для множества DNS зон.

### ISSUE THREAD

**Issue by katerkoff** [malinink/cert-manager-webhook-yandex-cloud#3]
Подскажите пожалуйста, как правильно осуществлять запрос, сразу для нескольких DNS зон?

Пробовал так, однако cert-manager постоянно жаловался, что не может создать запись _acme-challenge.dns.zone-2 , т.к. она не принадлежит к dns.zone1. Т.е. почему-то пытается создать запись одной зоны, в другой.

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: yc-dns-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: example@example.com
    privateKeySecretRef:
      name: yc-dns-letsencrypt
    solvers:
       - dns01:
           webhook:
             groupName: acme.cloud.yandex.ru
             solverName: yandex-cloud
             config:
               dnsZoneId: ${data.yandex_dns_zone.dns-zone-1.id}
               authorizationKeySecretName: yc-auth-key
      - dns01:
          webhook:
            groupName: acme.cloud.yandex.ru
            solverName: yandex-cloud
            config:
              dnsZoneId: ${data.yandex_dns_zone.dns-zone-2.id}
              authorizationKeySecretName: yc-auth-key
```

Так же пробовал прописать несколько DNS зон в dnsZoneId, через запятую, так он тоже не смог.
